const animalImages = {
  "African Lion": "assets/images/African Lion.jpg",
  "Bengal Tiger": "assets/images/Bengal Tiger.jpg",
  "Leopard": "assets/images/Leopard.jpg",
  "Cheetah": "assets/images/Cheetah.jpg",
  "African Elephant": "assets/images/African Elephant.jpg",
  "Giraffe": "assets/images/Giraffe.jpg",
  "Zebra": "assets/images/Zebra.jpg",
  "Hippopotamus": "assets/images/Hippopotamus.jpg",
  "Rhinoceros": "assets/images/Rhinoceros.jpg",
  "Camel": "assets/images/Camel.jpg",
  "Kangaroo": "assets/images/Kangaroo.jpg",
  "Giant Panda": "assets/images/Panda.jpg",
  "Brown Bear": "assets/images/Brown Bear.jpg",
  "Polar Bear": "assets/images/Polar Bear.jpg",
  "Gray Wolf": "assets/images/Gray Wolf.jpg",
  "Red Fox": "assets/images/Red Fox.jpg",
  "Spotted Hyena": "assets/images/Spotted Hyena.jpg",
  "White-Tailed Deer": "assets/images/White-Tailed Deer.jpg",
  "Moose": "assets/images/Moose.jpg",
  "American Bison": "assets/images/American Bison.jpg",
  "African Buffalo": "assets/images/African Buffalo.jpg",
  "Mountain Gorilla": "assets/images/Mountain Gorilla.jpg",
  "Chimpanzee": "assets/images/Chimpanzee.jpg",
  "Bornean Orangutan": "assets/images/Bornean Orangutan.jpg",
  "Olive Baboon": "assets/images/Olive Baboon.jpg",
  "Ring-Tailed Lemur": "assets/images/Ring-Tailed Lemur.jpg",
  "Two-Toed Sloth": "assets/images/Two-Toed Sloth.jpg",
  "North American Otter": "assets/images/North American Otter.jpg",
  "Meerkat": "assets/images/Meerkat.jpg",
  "Common Raccoon": "assets/images/Common Raccoon.jpg",
  "Greater Flamingo": "assets/images/Greater Flamingo.jpg",
  "Indian Peacock": "assets/images/Indian Peacock.jpg",
  "Scarlet Macaw": "assets/images/Scarlet Macaw.jpg",
  "Bald Eagle": "assets/images/Bald Eagle.jpg",
  "Great Horned Owl": "assets/images/Great Horned Owl.jpg",
  "Emperor Penguin": "assets/images/Emperor Penguin.jpg",
  "Common Ostrich": "assets/images/Common Ostrich.jpg",
  "Saltwater Crocodile": "assets/images/Saltwater Crocodile.jpg",
  "American Alligator": "assets/images/American Alligator.jpg",
  "Galápagos Tortoise": "assets/images/Galápagos Tortoise.jpg",
  "King Cobra": "assets/images/King Cobra.jpg",
  "Komodo Dragon": "assets/images/Komodo Dragon.jpg",
  "Green Iguana": "assets/images/Green Iguana.jpg",
  "Bottlenose Dolphin": "assets/images/Bottlenose Dolphin.jpg",
  "California Sea Lion": "assets/images/California Sea Lion.jpg",
  "Gray Seal": "assets/images/Gray Seal.jpg",
  "Great White Shark": "assets/images/Great White Shark.jpg",
  "Blue-Spotted Stingray": "assets/images/Blue-Spotted Stingray.jpg",
  "Horse": "assets/images/Horse.jpg",
  "Goat": "assets/images/Goat.jpg"
};